import { expect, test } from '@playwright/test'
import { attach, watch } from './diagnostics'

test.beforeEach(async ({ page }) => watch(page))
test.afterEach(async ({ page }, info) => attach(page, info))

test('配置发布后从空方案运行并写入 Plate，刷新保留版本与引用', async ({ page, request }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '新建项目' }).click()
  await page.getByRole('dialog', { name: '新建项目' }).getByLabel('项目名称').fill(`配置验收 ${Date.now()}`)
  await page.getByRole('button', { name: '创建项目' }).click()
  const projectId = await page.getByLabel('切换项目').inputValue()
  await page.getByRole('navigation', { name: '主导航' }).getByRole('button', { name: '报告写作' }).click()
  await page.getByRole('button', { name: '规则与章节配置' }).click()
  await page.getByRole('button', { name: '新建版本' }).click()
  await page.getByRole('textbox', { name: '配置名称', exact: true }).fill('销售测算')
  await page.getByRole('button', { name: '创建', exact: true }).click()

  for (const [index, key, label, computed] of [
    [1, 'demand', '需求', false], [2, 'capacity', '能力', false], [3, 'sales', '销售', true],
  ] as const) {
    await page.getByRole('button', { name: '添加字段' }).click()
    await page.getByRole('textbox', { name: `字段 ${index} 标识` }).fill(key)
    await page.getByRole('textbox', { name: `字段 ${index} 名称` }).fill(label)
    await page.getByRole('textbox', { name: `字段 ${index} 单位` }).fill('套')
    await page.getByRole('textbox', { name: `字段 ${index} 分组` }).fill(index === 1 ? '需求' : index === 2 ? '产能' : '销售')
    if (computed) await page.getByRole('combobox', { name: `字段 ${index} 用途` }).selectOption('computed')
  }
  await page.getByRole('button', { name: '规则', exact: true }).click()
  await page.getByRole('button', { name: '添加规则' }).click()
  await page.getByRole('textbox', { name: '规则 1 标识' }).fill('sales_rule')
  await page.getByRole('textbox', { name: '规则 1 名称' }).fill('销售计算')
  await page.getByRole('combobox', { name: '规则 1 目标' }).selectOption('sales')
  await page.getByRole('textbox', { name: '规则 1 表达式' }).fill('min(demand, capacity)')
  await page.getByRole('button', { name: '章节', exact: true }).click()
  await page.getByRole('button', { name: '添加章节' }).click()
  await page.getByRole('textbox', { name: '章节 1 标识' }).fill('chapter-1')
  await page.getByRole('textbox', { name: '章节 1 标题' }).fill('销售测算')
  for (const label of ['需求 demand', '能力 capacity', '销售 sales']) await page.getByRole('checkbox', { name: label }).check()
  await page.getByRole('button', { name: '保存草稿' }).click()
  await page.getByRole('button', { name: '试算与发布' }).click()
  await page.getByRole('textbox', { name: '试算 需求' }).fill('300000')
  await page.getByRole('textbox', { name: '试算 能力' }).fill('254016')
  await page.getByRole('button', { name: '试算', exact: true }).click()
  await expect(page.locator('.analysis-config-results')).toContainText('254016')
  await page.getByRole('button', { name: '发布 v1' }).click()
  await expect(page.getByText('v1 · 已发布')).toBeVisible()
  await page.setViewportSize({ width: 900, height: 700 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.setViewportSize({ width: 500, height: 700 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.setViewportSize({ width: 1280, height: 800 })

  await page.getByRole('button', { name: '返回报告' }).click()
  await page.getByRole('button', { name: '新建报告' }).click()
  await page.getByRole('textbox', { name: '报告标题' }).fill('配置写作验收报告')
  await page.getByRole('button', { name: '创建', exact: true }).click()
  await page.getByRole('button', { name: '输入数据' }).click()
  await page.getByText('按已发布配置创建方案').click()
  await page.getByRole('button', { name: '创建空输入方案' }).click()
  await expect(page.getByRole('heading', { name: '需求', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '产能', exact: true })).toBeVisible()
  await expect(page.getByRole('spinbutton', { name: '需求' })).toBeVisible()
  await expect(page.getByRole('spinbutton', { name: '能力' })).toBeVisible()
  await page.getByRole('spinbutton', { name: '需求' }).fill('300000')
  await page.getByRole('spinbutton', { name: '能力' }).fill('254016')
  await page.getByRole('button', { name: '预览推演' }).click()
  await expect(page.locator('.scenario-preview')).toContainText('254016')
  await page.getByRole('button', { name: '保存方案并运行' }).click()
  await page.getByRole('button', { name: '用于报告' }).click()
  await page.getByRole('button', { name: '确认采用' }).click()
  await page.getByRole('button', { name: '生成本章', exact: true }).click()
  await page.getByRole('button', { name: '生成候选' }).click()
  await expect(page.locator('.scenario-candidate')).toContainText('254016')
  await page.getByRole('button', { name: '加入报告' }).click()
  await expect(page.locator('[contenteditable="true"]')).toContainText('254016')
  await page.reload()
  await expect(page.locator('[contenteditable="true"]')).toContainText('254016')
  const reports = await request.get(`/api/projects/${projectId}/reports`)
  expect(reports.ok()).toBeTruthy()
  const rows = await reports.json() as { id: string; title: string }[]
  const reportId = rows.find((row) => row.title === '配置写作验收报告')?.id
  expect(reportId, JSON.stringify(rows)).toBeTruthy()
  const report = await request.get(`/api/projects/${projectId}/reports/${reportId}`)
  expect(report.ok(), await report.text()).toBeTruthy()
  const body = await report.json() as { content: { analysis_refs?: { result_key: string }[] }[] }
  expect(body.content.some((block) => block.analysis_refs?.some((ref) => ref.result_key === 'sales'))).toBeTruthy()
})
